<?php

$router->define([
    '' => 'app/views/auth/Login.view.php',
    'signup' => 'app/views/auth/Signup.view.php',
    'gmail' => 'app/controllers/auth/GmailAuth.controller.php',
    'activation' => 'app/controllers/auth/Verification.controller.php',
    'admin' => 'app/views/users/admin.view.php',
    'user' => 'app/views/users/reader.view.php',
    'logout' => 'app/controllers/auth/Logout.controller.php',
    'books' => 'app/controllers/books/Books.controller.php',
    'addBook' => 'app/views/books/AddBook.view.php',
    'listuser' => 'app/views/users/List.view.php',
    'edit' => 'app/views/books/EditBook.view.php',
    'delete' => 'app/controllers/books/DeleteBook.controller.php',
    'deleteuser' => 'app/controllers/users/DeleteUser.controller.php',
    'login' => 'app/controllers/auth/Login.controller.php',
    'signed' => 'app/controllers/auth/Signup.controller.php',
    'AddBook' => 'app/controllers/books/Addbook.controller.php',
    'editbook' => 'app/controllers/books/EditBook.controller.php',
    'readbook' => 'app/controllers/books/ReadBook.controller.php',
    'unreadbook' => 'app/controllers/books/UnreadBook.controller.php',
    'verifymail' => 'app/views/users/Verify.view.php',
    '404' => 'app/views/auth/Pagenotfound.view.php',
    'categories' => 'app/views/books/Categories.view.php',
    'deletecategories' => 'app/controllers/books/DeleteCategories.controller.php',
    'addCat' => 'app/controllers/books/AddCategory.controller.php',
    'forgot' => 'app/views/auth/ForgotPassword.view.php',
    'message' => 'app/views/auth/ForgotPassMessage.view.php',
    'forgotpass' => 'app/controllers/auth/ForgotPassword.controller.php',
    'resetpass' => 'app/controllers/auth/ResetPassword.controller.php',
    'reset' => 'app/views/auth/ResetPassword.view.php',
    'resetmsg' => 'app/views/auth/ResetMessage.view.php',
    'activated' => 'app/views/auth/AccountActivatedMessage.view.php'
]);

